# Generated by Django 4.2.17 on 2025-03-24 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('training', 'Training'), ('testing', 'Testing')], max_length=20)),
                ('speed', models.FloatField(help_text='Speed in ms (Training) or Hz (Testing)')),
                ('time_limit', models.IntegerField(help_text='Time limit in seconds')),
                ('selection_timeout', models.IntegerField(help_text='Selection timeout in ms')),
                ('central_to_selection_gap', models.IntegerField(help_text='Gap after central light in ms')),
                ('selection_to_central_gap', models.IntegerField(help_text='Gap after selection in ms')),
                ('screen_size', models.FloatField(help_text='Screen size in inches')),
                ('viewing_distance', models.FloatField(help_text='Viewing distance in cm')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], max_length=20)),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('missed', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0, help_text='Accuracy in percentage')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='myapp.sessionsettings')),
            ],
        ),
    ]
